TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Dotpulse.Emergency': true
    userInterface:
      translation:
        autoInclude:
          'Dotpulse.Emergency': ['NodeTypes/*']

Dotpulse:
  Emergency:
    contextOverall:
      targetDimensions:
        region: global
      dimensions:
        region: ['global']
